name: PythonDataNBA
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2021.11
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.9.0
  - anaconda-project=0.10.2
  - anyio=2.2.0
  - appdirs=1.4.4
  - argcomplete=1.12.3
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astroid=2.6.6
  - astropy=4.3.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.0
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  #- comtypes=1.1.10
  - conda=4.11.0
  - conda-content-trust=0.1.1
  - conda-pack=0.6.0
  - conda-package-handling=1.7.3
  - conda-token=0.3.0
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=35.0.0
  - curl=7.78.0
  - cycler=0.11.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - daal4py=2021.4.0
  - dal=2021.4.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docutils=0.17.1
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - fastcache=1.1.0
  - filelock=3.4.0
  - flake8=3.9.2
  - flask=1.1.2
  - fonttools=4.25.0
  - freetype=2.10.4
  - fsspec=2021.10.1
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - giflib=5.2.1
  - glob2=0.7
  - greenlet=1.1.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  #- icc_rt=2019.0.0
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.3.0
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.0
  - keyring=23.4.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcurl=7.78.0
  - libdeflate=1.8
  - libiconv=1.15
  - liblief=0.10.1
  - libpng=1.6.37
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.37.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
 # - m2w64-gcc-libgfortran=5.3.0
  #- m2w64-gcc-libs=5.3.0
 #- m2w64-gcc-libs-core=5.3.0
 # - m2w64-gmp=6.1.0
  #- m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
 # - menuinst=1.4.18
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.12.0
  - mpmath=1.2.1
  - msgpack-python=1.0.2
 # - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.6
  - numba=0.54.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.8.2
  - partd=1.2.0
  - path=16.0.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - patsy=0.5.2
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pkginfo=1.7.1
  - pluggy=0.13.1
  - ply=3.11
 # - powershell_shortcut=0.0.1
  - poyo=0.5.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycrypto=2.6.1
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pynacl=1.4.0
  - pyodbc=4.0.31
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
 # - pyreadline=2.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - python=3.7.11
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python_abi=3.7
  - pytz=2021.3
  - pywavelets=1.1.1
  #- pywin32=228
  #- pywin32-ctypes=0.2.0
  #- pywinpty=0.5.7
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - regex=2021.8.3
  - requests=2.26.0
  - rope=0.21.1
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.18.3
  - scikit-learn=1.0.1
  - scikit-learn-intelex=2021.4.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.8
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.27
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - sympy=1.9
  - tabulate=0.8.9
  - tbb=2021.4.0
  - tbb4py=2021.4.0
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - urllib3=1.26.7
  #- vc=14.2
  #- vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.0
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  #- win_inet_pton=1.1.0
  #- win_unicode_console=0.5
  #- wincertstore=0.2
  #- winpty=0.4.3
  - wrapt=1.12.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.2
  - xlwings=0.24.9
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - bs4==0.0.1
    - colorcet==3.0.0
    - configparser==5.2.0
    - crayons==0.4.0
    - flask-pymongo==2.3.0
    - flask-sqlalchemy==2.5.1
    - h11==0.13.0
    - holoviews==1.14.8
    - hvplot==0.7.3
    - markdown==3.3.6
    - nba-api==1.1.11
    - outcome==1.1.0
    - panel==0.12.6
    - param==1.12.0
    - psycopg2-binary==2.9.3
    - pyct==0.4.8
    - pymongo==4.0.1
    - pyviz-comms==2.1.0
    - selenium==4.1.0
    - splinter==0.17.0
    - trio==0.19.0
    - trio-websocket==0.9.2
    - webdriver-manager==3.5.2
    - wsproto==1.0.0
     - msys2-conda-epoch=20160418


# prefix: C:\Users\cdpet\anaconda3\envs\PythonDataNBA
